### ISSUE TITLE
Trade Command: Roles deleted even if they have 1 left

### ISSUE THREAD

**Issue by sarbjotm** [sarbjotm/Kiwi#13]
Database shows user has a role left however the role is removed from the user

**Comment by Sarbjotm** [comment]
c.fetchone()[0] results in NoneType so it doesn't use the for loop

**Comment by sarbjotm** [comment]
Potential Errors: 

- NoneType returned since c.fetchone() is used multiple times
- c.fetchone()[0] doesn't return correct number (check in print logs)

**Comment by sarbjotm** [comment]
Fixed 01-22-21
