### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by sarbjotm** [sarbjotm/Kiwi#60]
Refactor Code to make it more user friendly

**Comment by sarbjotm** [comment]
- Error messages revamped
- Large strings split into multiple lines using '\'

**Comment by sarbjotm** [comment]
Blackjack refactored
- Removed extra elif statements
- Combined if statements when output was the same
- Changed embed colours

**Comment by EarthenSky** [comment]
I will look into implementing a `myconstants.py` module for keeping data structures such as zodiac_signs and rolesList / activateRoles consistent between cogs. I'll also convert all pascalCase variables to snake_case for consistency.
