### ISSUE TITLE
Fix Weather Module

### ISSUE THREAD

**Issue by EarthenSky** [sarbjotm/Kiwi#83]
The ,weather <city> command is reporting KeyError: 'BASE_URL' on the latest version of the dev branch.

**Comment by sarbjotm** [comment]
Will add config values for DEV branch

**Comment by sarbjotm** [comment]
Added API_KEY and BASE_URL to Config values on Heroku Server

**Comment by sarbjotm** [comment]
Works perfectly in dev branch/server now!
